export type { AppStatusDto } from './generated/AppStatusDto';
export type { AudioDeviceDto } from './generated/AudioDeviceDto';
export type { AudioDiagnosticsDto } from './generated/AudioDiagnosticsDto';
export type { AudioLevelEventDto } from './generated/AudioLevelEventDto';
export type { DeviceFallbackEventDto } from './generated/DeviceFallbackEventDto';
export type { SttPhaseDto } from './generated/SttPhaseDto';
export type { SttStateEventDto } from './generated/SttStateEventDto';
export type { TranscriptEventDto } from './generated/TranscriptEventDto';
export type { CharacterCursorEventDto } from './generated/CharacterCursorEventDto';
export type { CharacterManifestDto } from './generated/CharacterManifestDto';
export type { CharacterRendererDto } from './generated/CharacterRendererDto';
export type { CharacterRendererKindDto } from './generated/CharacterRendererKindDto';
export type { CharacterSettingsChangedEventDto } from './generated/CharacterSettingsChangedEventDto';
export type { CharacterSettingsDto } from './generated/CharacterSettingsDto';
export type { CharacterSetupDto } from './generated/CharacterSetupDto';
export type { CharacterSourceStatusDto } from './generated/CharacterSourceStatusDto';
export type { StaticExpressionDto } from './generated/StaticExpressionDto';
export type { ChatMessageEventDto } from './generated/ChatMessageEventDto';
export type { ChatPlacementDto } from './generated/ChatPlacementDto';
export type { ChatRoleDto } from './generated/ChatRoleDto';
export type { ConversationMessageDto } from './generated/ConversationMessageDto';
export type { ConversationLogPageDto } from './generated/ConversationLogPageDto';
export type { ConversationHistoryDeletedEventDto } from './generated/ConversationHistoryDeletedEventDto';
export type { ConversationStateDto } from './generated/ConversationStateDto';
export type { ConversationStateEventDto } from './generated/ConversationStateEventDto';
export type { LlmSettingsDto } from './generated/LlmSettingsDto';
export type { MotionGroupDto } from './generated/MotionGroupDto';
export type { SpeechAudioEventDto } from './generated/SpeechAudioEventDto';
export type { SpeechStopEventDto } from './generated/SpeechStopEventDto';
export type { TtsSettingsDto } from './generated/TtsSettingsDto';
export type { TtsSpeakerDto } from './generated/TtsSpeakerDto';
export type { TtsStateEventDto } from './generated/TtsStateEventDto';
export type { UserDictWordDto } from './generated/UserDictWordDto';
export type { FailureClassDto } from './generated/FailureClassDto';
export type { HealthStatusDto } from './generated/HealthStatusDto';
export type { RuntimeFeatureDto } from './generated/RuntimeFeatureDto';
export type { RuntimeHealthEventDto } from './generated/RuntimeHealthEventDto';
export type { QueueMetricsDto } from './generated/QueueMetricsDto';
export type { RuntimeDiagnosticsDto } from './generated/RuntimeDiagnosticsDto';
export type { DiagnosticReportDto } from './generated/DiagnosticReportDto';
export type { FrontendDiagnosticDto } from './generated/FrontendDiagnosticDto';
export type { FrontendErrorKindDto } from './generated/FrontendErrorKindDto';
export type { TechnicalLogChunkDto } from './generated/TechnicalLogChunkDto';
export type { TechnicalLogCursorDto } from './generated/TechnicalLogCursorDto';
export type { ThemePreferenceDto } from './generated/ThemePreferenceDto';
export type { UiPreferencesDto } from './generated/UiPreferencesDto';
export type { UpdateStateDto } from './generated/UpdateStateDto';
export type { UpdateStatusDto } from './generated/UpdateStatusDto';

export const CHARACTER_MANIFEST_SCHEMA_VERSION = 2;
export const CHARACTER_SETTINGS_SCHEMA_VERSION = 2;
export const CHARACTER_SETUP_SCHEMA_VERSION = 1;
export const CHARACTER_SETTINGS_CHANGED_EVENT = 'character-settings-changed';
