[[permission]]
identifier = "allow-report-runtime-success"
description = "Enables the report_runtime_success command without any pre-configured scope."
commands.allow = ["report_runtime_success"]

[[permission]]
identifier = "deny-report-runtime-success"
description = "Denies the report_runtime_success command without any pre-configured scope."
commands.deny = ["report_runtime_success"]
